USE [master]
GO
/****** Object:  Database [pharmacy]    Script Date: 11.04.2022 13:02:16 ******/
CREATE DATABASE [pharmacy]
GO
ALTER DATABASE [pharmacy] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pharmacy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [pharmacy] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [pharmacy] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [pharmacy] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [pharmacy] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [pharmacy] SET ARITHABORT OFF 
GO
ALTER DATABASE [pharmacy] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [pharmacy] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [pharmacy] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [pharmacy] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [pharmacy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [pharmacy] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [pharmacy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [pharmacy] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [pharmacy] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [pharmacy] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [pharmacy] SET  DISABLE_BROKER 
GO
ALTER DATABASE [pharmacy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [pharmacy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [pharmacy] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [pharmacy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [pharmacy] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [pharmacy] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [pharmacy] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [pharmacy] SET RECOVERY FULL 
GO
ALTER DATABASE [pharmacy] SET  MULTI_USER 
GO
ALTER DATABASE [pharmacy] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [pharmacy] SET DB_CHAINING OFF 
GO
ALTER DATABASE [pharmacy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [pharmacy] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [pharmacy]
GO
/****** Object:  Table [dbo].[Pharmacy]    Script Date: 11.04.2022 13:02:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Pharmacy](
	[pharmacy_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](200) NOT NULL,
	[address] [varchar](50) NULL,
	[phone] [bigint] NULL,
 CONSTRAINT [PK_Pharmacy_pharmacy_id] PRIMARY KEY CLUSTERED 
(
	[pharmacy_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Product]    Script Date: 11.04.2022 13:02:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[product_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_Product_product_id] PRIMARY KEY CLUSTERED 
(
	[product_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Storage]    Script Date: 11.04.2022 13:02:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Storage](
	[storage_id] [int] IDENTITY(1,1) NOT NULL,
	[pharmacy_id] [int] NOT NULL,
	[name] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_Storage_storage_id] PRIMARY KEY CLUSTERED 
(
	[storage_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Supply]    Script Date: 11.04.2022 13:02:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Supply](
	[supply_id] [int] IDENTITY(1,1) NOT NULL,
	[product_id] [int] NOT NULL,
	[storage_id] [int] NOT NULL,
	[quantity] [int] NOT NULL,
 CONSTRAINT [PK_Supply_supply_id] PRIMARY KEY CLUSTERED 
(
	[supply_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Index [KEY_Pharmacy_pharmacy_id]    Script Date: 11.04.2022 13:02:16 ******/
CREATE UNIQUE NONCLUSTERED INDEX [KEY_Pharmacy_pharmacy_id] ON [dbo].[Pharmacy]
(
	[pharmacy_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [KEY_Product_product_id]    Script Date: 11.04.2022 13:02:16 ******/
CREATE UNIQUE NONCLUSTERED INDEX [KEY_Product_product_id] ON [dbo].[Product]
(
	[product_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [KEY_Storage_storage_id]    Script Date: 11.04.2022 13:02:16 ******/
CREATE UNIQUE NONCLUSTERED INDEX [KEY_Storage_storage_id] ON [dbo].[Storage]
(
	[storage_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Storage]  WITH CHECK ADD  CONSTRAINT [FK_Storage_pharmacy] FOREIGN KEY([pharmacy_id])
REFERENCES [dbo].[Pharmacy] ([pharmacy_id])
GO
ALTER TABLE [dbo].[Storage] CHECK CONSTRAINT [FK_Storage_pharmacy]
GO
ALTER TABLE [dbo].[Supply]  WITH CHECK ADD  CONSTRAINT [FK_Supply_product] FOREIGN KEY([product_id])
REFERENCES [dbo].[Product] ([product_id])
GO
ALTER TABLE [dbo].[Supply] CHECK CONSTRAINT [FK_Supply_product]
GO
ALTER TABLE [dbo].[Supply]  WITH CHECK ADD  CONSTRAINT [FK_Supply_storage] FOREIGN KEY([storage_id])
REFERENCES [dbo].[Storage] ([storage_id])
GO
ALTER TABLE [dbo].[Supply] CHECK CONSTRAINT [FK_Supply_storage]
GO
USE [master]
GO
ALTER DATABASE [pharmacy] SET  READ_WRITE 
GO